package me.neoblade298.neorogue.session.event;

public enum SessionTrigger {
	REWARD_FIGHT,
	CLEAR_REWARDS,
	GENERATE_SHOP,
	VISIT_NODE,
	ENTER_NODE_SELECT,
	OPEN_SESSION_INVENTORY,
	OPEN_GLOSSARY,
	OPEN_TUTORIAL_BOOK,
	WIN_MINIBOSS,
	WIN_BOSS,
	SPEND_CURRENCY,
	CURRENCY_CHANGED,
	LEAVE_SHOP,
	CROWN_EARNED,
	MAX_STAT_CHANGED,
	EQUIPMENT_LAYOUT_CHANGED,
	ACQUIRE_EQUIPMENT,
	FINISH_RUN,
	WIN_RUN;
}
