package me.neoblade298.neorogue.session.event;

public enum SessionTrigger {
	REWARD_FIGHT,
	CLEAR_REWARDS,
	GENERATE_SHOP,
	VISIT_NODE,
	ENTER_NODE_SELECT,
	OPEN_SESSION_INVENTORY,
	OPEN_GLOSSARY,
	WIN_MINIBOSS,
	WIN_BOSS,
	SPEND_COINS,
	ACQUIRE_EQUIPMENT,
	FINISH_RUN;
}
