name: NeoRogue
main: me.neoblade298.neorogue.NeoRogue
authors: [Ascheladd, FoPzl]
depend: [NeoCore, Vault, AshEconomy, AshStore, Essentials, EssentialsSpawn]
softdepend: [WorldEdit, PlaceholderAPI, MythicMobs, TownyFlight]
version: 1.0
api-version: 1.20
commands:
   nr:
      description: NeoRogue General command
      permission: neorogue.general
   nradmin:
      aliases: [nra]
      description: NeoRogue Admin command
      permission: neorogue.admin
   nrflag:
      description: NeoRogue player flag management command
      permission: neorogue.admin
permissions:
   neorogue.general:
      description: Allows use of /nr commands
      default: true
      children:
         neorogue.session.host: true
         neorogue.session.join: true
         neorogue.session.spectate: true
         neorogue.profile.others: true
   neorogue.session.host:
      description: Allows hosting, loading, and deleting NeoRogue sessions
      default: false
   neorogue.session.join:
      description: Allows requesting to join NeoRogue sessions
      default: false
   neorogue.session.spectate:
      description: Allows spectating NeoRogue sessions
      default: false
   neorogue.profile.others:
      description: Allows viewing other players' NeoRogue profiles
      default: false
   neorogue.admin:
      description: Allows use of /nradmin commands
      default: op
      children:
         neorogue.leaderboards.manage: true
   neorogue.leaderboards.manage:
      description: Allows managing leaderboard display locations
      default: op
   neorogue.slots.2:
    description: Grants 2 save slots
    default: false
   neorogue.slots.3:
    description: Grants 3 save slots
    default: false
   neorogue.slots.5:
    description: Grants 5 save slots
    default: false
   neorogue.expboost.iron:
      description: Grants a 10% exp boost for each run
      default: false
   neorogue.expboost.gold:
      description: Grants a 25% exp boost for each run
      default: false
   neorogue.expboost.diamond:
      description: Grants a 50% exp boost for each run
      default: false
   neorogue.expboost.netherite:
      description: Grants a 100% exp boost for each run
      default: false