name: NeoRogue
main: me.neoblade298.neorogue.NeoRogue
author: [Neoblade298]
depend: [NeoCore, WorldEdit, HolographicDisplays]
softdepend: [MythicMobs]
version: 1.0
api-version: 1.16
commands:
   nradmin:
      description: NeoRogue Admin command