name: NeoRogue
main: me.neoblade298.neorogue.NeoRogue
author: [Ascheladd]
depend: [NeoCore, WorldEdit, DecentHolograms]
softdepend: [MythicMobs]
version: 1.0
api-version: 1.16
commands:
   nr:
      description: NeoRogue General command
   nradmin:
      aliases: [nra]
      description: NeoRogue Admin command