name: NeoRogue
main: me.neoblade298.neorogue.NeoRogue
author: [Neoblade298]
depend: [NeoCore]
version: 1.0
api-version: 1.16
commands:
   disenchant:
      description: This command allows you to disenchant item in hand
      usage: /disenchant
      permission: disenchant.true