name: NeoRogue
main: me.neoblade298.neorogue.NeoRogue
authors: [Ascheladd, FoPzl]
depend: [NeoCore, WorldEdit, DecentHolograms, PlaceholderAPI]
softdepend: [MythicMobs]
version: 1.0
api-version: 1.20
commands:
   nr:
      description: NeoRogue General command
   nradmin:
      aliases: [nra]
      description: NeoRogue Admin command